package primero;

// Generated 05-nov-2014 16:30:22 by Hibernate Tools 3.4.0.CR1

/**
 * Departamentos generated by hbm2java
 */
public class Departamentos implements java.io.Serializable {

	private int deptNo;
	private String dnombre;
	private String loc;

	public Departamentos() {
	}

	public Departamentos(int deptNo) {
		this.deptNo = deptNo;
	}

	public Departamentos(int deptNo, String dnombre, String loc) {
		this.deptNo = deptNo;
		this.dnombre = dnombre;
		this.loc = loc;
	}

	public int getDeptNo() {
		return this.deptNo;
	}

	public void setDeptNo(int deptNo) {
		this.deptNo = deptNo;
	}

	public String getDnombre() {
		return this.dnombre;
	}

	public void setDnombre(String dnombre) {
		this.dnombre = dnombre;
	}

	public String getLoc() {
		return this.loc;
	}

	public void setLoc(String loc) {
		this.loc = loc;
	}

}
