package primero;

// Generated 05-nov-2014 16:30:22 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Empleados generated by hbm2java
 */
public class Empleados implements java.io.Serializable {

	private int empNo;
	private String nombre;
	private Date fechaAlt;
	private String localidad;
	private Integer salario;
	private int deptNo;

	public Empleados() {
	}

	public Empleados(int empNo, int deptNo) {
		this.empNo = empNo;
		this.deptNo = deptNo;
	}

	public Empleados(int empNo, String nombre, Date fechaAlt, String localidad,
			Integer salario, int deptNo) {
		this.empNo = empNo;
		this.nombre = nombre;
		this.fechaAlt = fechaAlt;
		this.localidad = localidad;
		this.salario = salario;
		this.deptNo = deptNo;
	}

	public int getEmpNo() {
		return this.empNo;
	}

	public void setEmpNo(int empNo) {
		this.empNo = empNo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFechaAlt() {
		return this.fechaAlt;
	}

	public void setFechaAlt(Date fechaAlt) {
		this.fechaAlt = fechaAlt;
	}

	public String getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

	public Integer getSalario() {
		return this.salario;
	}

	public void setSalario(Integer salario) {
		this.salario = salario;
	}

	public int getDeptNo() {
		return this.deptNo;
	}

	public void setDeptNo(int deptNo) {
		this.deptNo = deptNo;
	}

}
