package primero;

// Generated 04-nov-2014 18:37:09 by Hibernate Tools 3.4.0.CR1

/**
 * Productos generated by hbm2java
 */
public class Productos implements java.io.Serializable {

	private int id;
	private String descripcion;
	private Integer stockActual;
	private Integer stockMinimo;
	private Short pvp;

	public Productos() {
	}

	public Productos(int id) {
		this.id = id;
	}

	public Productos(int id, String descripcion, Integer stockActual,
			Integer stockMinimo, Short pvp) {
		this.id = id;
		this.descripcion = descripcion;
		this.stockActual = stockActual;
		this.stockMinimo = stockMinimo;
		this.pvp = pvp;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Integer getStockActual() {
		return this.stockActual;
	}

	public void setStockActual(Integer stockActual) {
		this.stockActual = stockActual;
	}

	public Integer getStockMinimo() {
		return this.stockMinimo;
	}

	public void setStockMinimo(Integer stockMinimo) {
		this.stockMinimo = stockMinimo;
	}

	public Short getPvp() {
		return this.pvp;
	}

	public void setPvp(Short pvp) {
		this.pvp = pvp;
	}

}
