package primero;

// Generated 04-nov-2014 18:37:09 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Ventas generated by hbm2java
 */
public class Ventas implements java.io.Serializable {

	private int idV;
	private Date fechaVenta;
	private String idCli;
	private int idPro;
	private Integer cantidad;

	public Ventas() {
	}

	public Ventas(int idV, String idCli, int idPro) {
		this.idV = idV;
		this.idCli = idCli;
		this.idPro = idPro;
	}

	public Ventas(int idV, Date fechaVenta, String idCli, int idPro,
			Integer cantidad) {
		this.idV = idV;
		this.fechaVenta = fechaVenta;
		this.idCli = idCli;
		this.idPro = idPro;
		this.cantidad = cantidad;
	}

	public int getIdV() {
		return this.idV;
	}

	public void setIdV(int idV) {
		this.idV = idV;
	}

	public Date getFechaVenta() {
		return this.fechaVenta;
	}

	public void setFechaVenta(Date fechaVenta) {
		this.fechaVenta = fechaVenta;
	}

	public String getIdCli() {
		return this.idCli;
	}

	public void setIdCli(String idCli) {
		this.idCli = idCli;
	}

	public int getIdPro() {
		return this.idPro;
	}

	public void setIdPro(int idPro) {
		this.idPro = idPro;
	}

	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

}
